[package]
name = "ipslim"
version = "1.0.0"
authors = ["Bourgond Aries <macocio@gmail.com>"]

[dependencies]
clippy = { version = "0.0.79", optional = true }

[features]
default = []
dev = ["clippy"]
